version: '3.8'

# Common configuration for all services
x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - solow-network

# Common healthcheck configuration
x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

services:
  # Main server - Unified Express + Socket.IO server
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    container_name: china-growth-game-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - ECONOMIC_MODEL_URL=http://model:8000
      - ALLOWED_ORIGINS=http://localhost:3000
      - USE_MOCK_MODEL=false
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - model
    restart: unless-stopped
    networks:
      - china-growth-net

  # Economic model - Python FastAPI service
  model:
    build:
      context: ./economic-model
      dockerfile: ../docker/model.Dockerfile
    container_name: china-growth-model
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./economic-model:/app
    restart: unless-stopped
    networks:
      - china-growth-net

  # Frontend - React app (development)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: china-growth-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_SOCKET_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - china-growth-net

networks:
  china-growth-net:
    driver: bridge

volumes:
  frontend_node_modules:
    name: solow-game-frontend-modules-${ENV_SUFFIX:-dev}
  backend_node_modules:
    name: solow-game-backend-modules-${ENV_SUFFIX:-dev}
  model_python_deps:
    name: solow-game-model-deps-${ENV_SUFFIX:-dev}
