version: "3.8"

# Common configuration for all services
x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - solow-network

# Common healthcheck configuration
x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

services:
  frontend:
    <<: *service-defaults
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_WS_URL=ws://localhost:4000
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]

  backend:
    <<: *service-defaults
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      model:
        condition: service_healthy
    environment:
      - PORT=4000
      - MODEL_API_URL=http://model:8000
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]

  model:
    <<: *service-defaults
    build:
      context: ./economic_model_py
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]

networks:
  solow-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules:
  model_python_deps: