version: '3.8'

# Common configuration for all services
x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - solow-network

# Common healthcheck configuration
x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 5s

# Common resource limits for production
x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 512M

services:
  # Main server - Unified Express + Socket.IO server
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    container_name: china-growth-game-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - ECONOMIC_MODEL_URL=http://model:8000
      - ALLOWED_ORIGINS=https://your-production-domain.com
      - USE_MOCK_MODEL=false
    restart: unless-stopped
    networks:
      - china-growth-net

  # Economic model - Python FastAPI service
  model:
    build:
      context: ./economic-model
      dockerfile: ../docker/model.Dockerfile
    container_name: china-growth-model
    # No port exposed in production - accessed only through internal network
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_ENV=production
    restart: unless-stopped
    networks:
      - china-growth-net

  # Frontend - Nginx server with built React app
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: china-growth-frontend
    ports:
      - "80:3000"
      - "443:3443"  # For HTTPS
    restart: unless-stopped
    networks:
      - china-growth-net
    # Add volumes for SSL certificates if needed
    # volumes:
    #  - /etc/letsencrypt:/etc/letsencrypt

networks:
  solow-network:
    driver: bridge
  china-growth-net:
    driver: bridge

volumes:
  model_data:
    name: solow_game_model_data_${ENV_SUFFIX:-prod}
    driver: local
