version: "3.8"

# Common configuration for all services
x-service-defaults: &service-defaults
  restart: unless-stopped
  networks:
    - solow-network

# Common healthcheck configuration
x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 5s

# Common resource limits for production
x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 512M

services:
  # Main application services
  frontend:
    <<: *service-defaults
    <<: *resource-limits
    build: 
      context: ./frontend
      dockerfile: ${DOCKER_PATH:-docker}/dockerfiles/Dockerfile.frontend.prod
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: ${FRONTEND_IMAGE}:${FRONTEND_VERSION}-prod
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - model
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "--fail", "http://localhost:80", "||", "exit", "1"]

  model:
    <<: *service-defaults
    build: 
      context: ./model
      dockerfile: ${DOCKER_PATH:-docker}/dockerfiles/Dockerfile.model.prod
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    image: ${MODEL_IMAGE}:${MODEL_VERSION}-prod
    ports:
      - "${MODEL_PORT:-8000}:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_ENV=production
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health", "||", "exit", "1"]
    volumes:
      - model_data:/app/data

  # China Growth Game services (optional, enabled via ENABLE_CHINA_GAME=true)
  china-game-frontend:
    <<: *service-defaults
    <<: *resource-limits
    profiles: ["china-game"]
    build:
      context: ./china-growth-game
      dockerfile: ${DOCKER_PATH:-docker}/dockerfiles/Dockerfile.china-frontend.prod
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: china-game-frontend:${FRONTEND_VERSION}-prod
    ports:
      - "${CHINA_FRONTEND_PORT:-81}:80"
    depends_on:
      - china-game-model
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "--fail", "http://localhost:80", "||", "exit", "1"]

  china-game-model:
    <<: *service-defaults
    profiles: ["china-game"]
    build:
      context: ./china-growth-game
      dockerfile: ${DOCKER_PATH:-docker}/dockerfiles/Dockerfile.china-model.prod
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    image: china-game-model:${MODEL_VERSION}-prod
    ports:
      - "${CHINA_MODEL_PORT:-8001}:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_ENV=production
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health", "||", "exit", "1"]
    volumes:
      - china_model_data:/app/data

networks:
  solow-network:
    driver: bridge

volumes:
  model_data:
    name: solow_game_model_data_${ENV_SUFFIX:-prod}
    driver: local
  china_model_data:
    name: china_game_model_data_${ENV_SUFFIX:-prod}
    driver: local
