FROM python:3.12.2-slim

WORKDIR /app

COPY economic-model/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY economic-model/ .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"] 